project: 
  summary: The linux OS base
  description: |
    This is the base OS linux ingredient, which is used as the base for all
    other chef packages built for linux.
  author: Philip Meulengracht
  email: the_meulengracht@hotmail.com
  version: 1.0.0
  license: MIT

environment:
  host:
    base: false
  build:
    confinement: false

recipes:
  - name: build-os
    path: ./
    steps:
    - name: construct
      type: script
      script: |
        # Packages for a basic linux/bash environment:
        PACKAGES=(
          libacl1
          libattr1
          libgmp10
          libc6-dev
          libgmp3-dev
          libmpc-dev
          binutils-dev
          libmpfr-dev
          libelf-dev
          zlib1g-dev
          gcc
          g++
          build-essential
          flex
          bison
          texinfo
        )

        delim=""
        joined=""
        for item in "${PACKAGES[@]}"; do
          joined="$joined$delim$item"
          delim=","
        done

        sudo debootstrap --variant=minbase --include="$joined" --arch=$[[ CHEF_TARGET_ARCHITECTURE ]] stable $[[ INSTALL_PREFIX ]] http://deb.debian.org/debian/
        sudo rm -rf $[[ INSTALL_PREFIX ]]/dev

packs:
- name: linux-1
  type: ingredient
