name: vchef
version: '1.0'
summary: The Vali Chef Package Mangement System
description: |
  Originally developed for the Vali/MollenOS operating system, this is a generic package management system that is 
  built as a lightweight alternative to current package managers. Its not only for package management, 
  but also as an application format. 

base: core20
grade: stable
confinement: strict

apps:
  bake:
    command: usr/bin/bake
  order:
    command: usr/bin/order
  serve:
    command: usr/bin/serve
  served:
    command: usr/bin/served
    daemon: simple
    install-mode: disable

parts:
  chef-src:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - libfuse3-dev
    stage-packages:
      - libfuse3-3
